name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb9376f2b77e5d225ccac548d8d9c113271a38117bc032d9ad16dc21a8c2a49d"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
