name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68fde3e997736cc7189f784097ce7d7e186355a4fba55cf45ff25ec30d447715"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
