name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05839c038d4703817e4a9cd11f7c5b1d469f6e9fc80ec98045300292c6bd2b50"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
