name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "111a5ee39be7109b422b6088eb48e5660e744db274d13e2e4aec379458d3168a"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
