name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ee7deae3314d426edd8540e0873d804dfb7231f50ecf56cc702c6753fb4ffa1"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
