name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20c4f6c177d144d59c25b7ec2f182aad01766867c4846a061a851aec11bcad3b"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
