name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "716eb44f5ec87bf3772364e68b470c8540d90510a0b7e62430d539cff2090b5e"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
