name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0823abe0373e639fc8fc4789b37d4bf0d010eb75573696a62491aee72e6e9d95"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
