name = "SteelPh0enix Modpack"
author = "SteelPh0enix"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fce847b5b84d5ef9bb58e9656ea2c5b715b141f42b9fdfb6a6a6f8ea53f94e0"

[versions]
fabric = "0.11.6"
minecraft = "1.16.5"
