name = "CraftPresence"
filename = "CraftPresence-Fabric-1.16.5-Release-1.8.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3437/565/CraftPresence-Fabric-1.16.5-Release-1.8.4.jar"
hash-format = "murmur2"
hash = "1467776183"

[update]
[update.curseforge]
file-id = 3437565
project-id = 297038
release-channel = "beta"
