name = "[Fabric] Expanded Storage"
filename = "expandedstorage-7.0.0-alpha.34+1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3382/387/expandedstorage-7.0.0-alpha.34+1.16.4.jar"
hash-format = "murmur2"
hash = "4045755640"

[update]
[update.curseforge]
file-id = 3382387
project-id = 317856
release-channel = "beta"
