name = "[Fabric] Expanded Storage"
filename = "expandedstorage-7.0.0+1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3409/602/expandedstorage-7.0.0+1.16.4.jar"
hash-format = "murmur2"
hash = "1367749221"

[update]
[update.curseforge]
file-id = 3409602
project-id = 317856
release-channel = "beta"
