name = "Fabric API"
filename = "fabric-api-0.38.1+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3432/308/fabric-api-0.38.1+1.16.jar"
hash-format = "murmur2"
hash = "3308259523"

[update]
[update.curseforge]
file-id = 3432308
project-id = 306612
release-channel = "beta"
