name = "Fabric API"
filename = "fabric-api-0.37.2+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3419/346/fabric-api-0.37.2+1.16.jar"
hash-format = "murmur2"
hash = "1244684524"

[update]
[update.curseforge]
file-id = 3419346
project-id = 306612
release-channel = "beta"
