name = "Fabric Language Kotlin"
filename = "fabric-language-kotlin-1.6.1+kotlin.1.5.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3330/753/fabric-language-kotlin-1.6.1+kotlin.1.5.10.jar"
hash-format = "murmur2"
hash = "3012870038"

[update]
[update.curseforge]
file-id = 3330753
project-id = 308769
release-channel = "beta"
