name = "Falling Leaves (Fabric)"
filename = "fallingleaves-1.6.0+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3289/593/fallingleaves-1.6.0+1.16.5.jar"
hash-format = "murmur2"
hash = "3618083106"

[update]
[update.curseforge]
file-id = 3289593
project-id = 417510
release-channel = "beta"
