name = "Inventory HUD+"
filename = "InventoryHUD-fabric-1.16.2-1.16.5-3.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3432/415/InventoryHUD-fabric-%5B1.16.2-1.16.5%5D-3.4.0.jar"
hash-format = "murmur2"
hash = "1500118247"

[update]
[update.curseforge]
file-id = 3432415
project-id = 357540
release-channel = "beta"
