name = "Iris Shaders"
filename = "iris-mc1.16.5-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3404/784/iris-mc1.16.5-1.1.1.jar"
hash-format = "murmur2"
hash = "2781087183"

[update]
[update.curseforge]
file-id = 3404784
project-id = 455508
release-channel = "beta"
