name = "LibCapableData (LibCD)"
filename = "libcd-3.0.3+1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3187/681/libcd-3.0.3+1.16.3.jar"
hash-format = "murmur2"
hash = "743259210"

[update]
[update.curseforge]
file-id = 3187681
project-id = 323710
release-channel = "beta"
