name = "Modern Industrialization"
filename = "Modern-Industrialization-0.4.0-alpha.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3386/664/Modern-Industrialization-0.4.0-alpha.11.jar"
hash-format = "murmur2"
hash = "2319897455"

[update]
[update.curseforge]
file-id = 3386664
project-id = 405388
release-channel = "beta"
