name = "Mod Menu"
filename = "modmenu-1.16.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3400/184/modmenu-1.16.11.jar"
hash-format = "murmur2"
hash = "3885857327"

[update]
[update.curseforge]
file-id = 3400184
project-id = 308702
release-channel = "beta"
