name = "Netherite Plus Mod"
filename = "netherite-plus-mod-1.4.5-1.16.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3334/125/netherite-plus-mod-1.4.5-1.16.5-fabric.jar"
hash-format = "murmur2"
hash = "2955518655"

[update]
[update.curseforge]
file-id = 3334125
project-id = 394120
release-channel = "beta"
