name = "WTHIT"
filename = "wthit-2.10.6-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3418/898/wthit-2.10.6-fabric.jar"
hash-format = "murmur2"
hash = "87284510"

[update]
[update.curseforge]
file-id = 3418898
project-id = 440979
release-channel = "beta"
