name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.14.0_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3396/272/Xaeros_Minimap_21.14.0_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "301771650"

[update]
[update.curseforge]
file-id = 3396272
project-id = 263420
release-channel = "beta"
