name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.15.0.1_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/75/Xaeros_Minimap_21.15.0.1_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "3849875546"

[update]
[update.curseforge]
file-id = 3420075
project-id = 263420
release-channel = "beta"
